### ISSUE TITLE
Forgotten line on part 3

### ISSUE THREAD

**Issue by atmorojo** [saswatds/elixir-rest-api#2]
Hello, thank you for this wonderful tutorial!

I'm currently on part 3 and encountered and error. After checking the code in this repo, I found out there's a forgotten line in the tutorial that is supposed to be written on `router.ex`
```elixir
alias RestApi.JSONUtils, as: JSON
```

I hope this could help those who encounters the same error as me. And again, thank you for this easy to follow tutorial!

**Comment by saswatds** [comment]
That's a good catch @atmorojo, really appreciate it. I have updated the post to add it.
